# Site settings
title: 青帝花神
email: 1312261976@qq.com
description: > # this means to ignore newlines until "baseurl:"
  欢迎某某人来我的blog呀~嘻嘻
baseurl: 
url: "http://xuecaihu.github.io" # the base hostname & protocol for your site
twitter_username: 
github_username:  XuecaiHu

# Build settings
markdown: kramdown
permalink: pretty
safe: false
rouge: true
excerpt_separrator: "\n\n\n"
paginate: 5