# Site settings
title: 青帝花神
email: 1312261976@qq.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: 
url: "http://xuecaihu.github.io" # the base hostname & protocol for your site
twitter_username: 
github_username:  XuecaiHu

# Build settings
markdown: kramdown
permalink: pretty
safe:false
pygments:true
excerpt_separrator:"\n\n\n"
paginate:5